- hosts: all
  vars:
        password: "Red"
  tasks:
        - name: create user
          user:
                name: "{{ item }}"
                state: present
                password: "{{ password | password_hash('sha512') }}"
          loop:
                - paltronics
          ignore_errors: yes
